language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - travis_retry composer update --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/coveralls -v
